{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dd-k8s-events.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dd-k8s-events.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "dd-k8s-events.serviceAccountName" . }}
rules:
- apiGroups:
  - ""
  - events.k8s.io
  resources:
  - events
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "dd-k8s-events.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "dd-k8s-events.serviceAccountName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "dd-k8s-events.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
